#!/bin/bash
HOOKDIR=$(dirname "$0")

git submodule status \
| sed -n -e 's/^\+/WARNING A SUBMODULE WAS ALREADY INITIALISED BUT TO A DIFFERENT COMMIT (consider `git submodule update`): /w/dev/stderr' \
         -e 's/^-[0-9a-z]\{40\} //p' \
| xargs -P 8 -n 1 bash $HOOKDIR/init-submod.sh

# Add relevant remotes to the submodules

(
unset $(git rev-parse --local-env-vars);
git -C cangjie_compiler remote add cjpluk-ssh git@github.com:CJPLUK/cangjie_compiler.git &> /dev/null
git -C cangjie_runtime remote add cjpluk-ssh git@github.com:CJPLUK/cangjie_runtime.git &> /dev/null
git -C cangjie_stdx remote add cjpluk-ssh git@github.com:CJPLUK/cangjie_stdx.git &> /dev/null
# git -C cangjie_tools remote add cjpluk-ssh # no repo on cjpluk github org

git -C cangjie_compiler remote add gitcode https://gitcode.com/Cangjie/cangjie_compiler.git &> /dev/null
git -C cangjie_runtime remote add gitcode https://gitcode.com/Cangjie/cangjie_runtime.git &> /dev/null
git -C cangjie_stdx remote add gitcode https://gitcode.com/Cangjie/cangjie_stdx.git &> /dev/null
git -C cangjie_tools remote add gitcode https://gitcode.com/Cangjie/cangjie_tools.git &> /dev/null
)


if [ "-$3" = "-1" ]; then
  git branch | sed -n 's;\* \([^(].*\);\1;p' | if read branchname; then # (branchnames cannot start with '(')
    for submod in cangjie_compiler cangjie_runtime cangjie_stdx; do
      git submodule status $submod | sed -e '/^[+-]/d' | read unused && (
        unset $(git rev-parse --local-env-vars);
        echo "Adding branch '$branchname' to $submod (if not present)"
        git -C $submod switch -q -c $branchname 2>&1 | sed '/fatal: a branch named .* already exists/d'
      )
    done
  fi
fi
