services:
  build-sdk:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
      args:
        - UID=${FIXUID:-1001}
    working_dir: /workspace
    environment:
      CANGJIE_VERSION: ${CANGJIE_VERSION:-0.0.1-dev}
      SDK_NAME: ${SDK_NAME:-unofficial}
      # OPENSSL_ROOT_DIR: /opt/buildtools/openssl-3.0.9
      # CMAKE_PREFIX_PATH: /opt/buildtools/openssl-3.0.9
    volumes:
      - ./:/workspace
    command: bash build_scripts/linux/all.sh
  dev:
    extends: build-sdk
    build:
      target: devcontainer
    command: bash -i
  opencode:
    extends: build-sdk
    build:
      target: opencode
    volumes:
      - type: bind
        source: /home/${USER}/.local/share/opencode/auth.json
        target: /home/dev/.local/share/opencode/auth.json
    command: /home/dev/.opencode/bin/opencode --agent containerized
